services:
  # Mongo_db service
  mongo_db:
    container_name: db_container
    image: mongo:4.4.6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
  #  Node API service
  api:
    container_name: api_container
    build: .
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: server_db
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
